services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=person_management'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'