spring:
  application:
    name: person_management_app
  datasource:
    url: jdbc:postgresql://localhost:5432/person_management
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs